services:
  postgres:
    image: postgres:16-alpine
    container_name: padosipro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: padosi
      POSTGRES_PASSWORD: padosi
      POSTGRES_DB: padosipro
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
