export const TASKS = [
  { title: 'Errands & Daily Tasks', description: 'Bills, banks, documents, government work', icon: 'check-square', comingSoon: false,
    kinds: ['Bills & Payments', 'Bank Work', 'Documents', 'Government Work'],
    services: ['Queue & paperwork handling', 'Pickup & drop', 'Bill payment help', 'Document collection'] },
  { title: 'Home Services', description: 'AC, plumbing, electrical, cleaning, repairs', icon: 'home', comingSoon: false,
    kinds: ['Repair', 'Cleaning', 'Installation'],
    services: ['AC service & repair', 'Plumber visit', 'Electrician visit', 'Deep cleaning'] },
  { title: 'Travel & Tourism', description: 'Flights, hotels, visas, transfers, itineraries', icon: 'map-pin', comingSoon: false,
    kinds: ['Book Travel', 'On-Trip Support', 'Documents & Visa', 'Local Transport'],
    services: ['Language & local guide support', 'Luggage handling & storage', 'SIM card & connectivity setup', 'Emergency travel changes handling'] },
  { title: 'Health & Medical', description: 'Doctor visits, pharmacy, labs, physio', icon: 'heart', comingSoon: false,
    kinds: ['Doctor Visit', 'Pharmacy', 'Lab Tests'], services: ['Appointment booking', 'Medicine pickup', 'Lab sample collection'] },
  { title: 'Senior Care', description: 'Check-ins, medicines, vitals, companionship', icon: 'users', comingSoon: false,
    kinds: ['Check-in', 'Medicines', 'Companionship'], services: ['Daily check-in call', 'Medicine reminders', 'Accompanied visits'] },
  { title: 'Events & Management', description: 'Weddings, décor, catering, photography', icon: 'calendar', comingSoon: false,
    kinds: ['Weddings', 'Décor', 'Catering'], services: ['Vendor coordination', 'Décor setup', 'Catering order'] },
  { title: 'Home Tech', description: 'WiFi, CCTV, smart locks, device repair', icon: 'wifi', comingSoon: false,
    kinds: ['Setup', 'Repair'], services: ['WiFi setup', 'CCTV installation', 'Device repair'] },
  { title: 'Relocation Services', description: 'Packers, movers, handover, paperwork', icon: 'truck', comingSoon: false,
    kinds: ['Packing', 'Moving'], services: ['Packers booking', 'Movers coordination', 'Handover paperwork'] },
  { title: 'NutriFix', description: 'Groceries, food delivery, diet plans, meal prep', icon: 'shopping-bag', comingSoon: true, kinds: [], services: [] },
  { title: 'Fashion & Styling', description: 'Salon at home, tailoring, styling, gifting', icon: 'scissors', comingSoon: true, kinds: [], services: [] },
  { title: 'Religious & Cultural', description: 'Pandit booking, puja, temple visits', icon: 'star', comingSoon: true, kinds: [], services: [] },
  { title: 'Business Support', description: 'Registration, GST, bookkeeping, compliance', icon: 'briefcase', comingSoon: true, kinds: [], services: [] },
  { title: 'Education Support', description: 'Tutors, admissions, exam prep', icon: 'book', comingSoon: true, kinds: [], services: [] },
  { title: 'Insurance & Loans', description: 'Compare policies, plan loans, paperwork handled', icon: 'shield', comingSoon: true, kinds: [], services: [] },
];
